"""
The botris engine module provides the core logic for the local runner botris engine.

Available subpackages
---------------------
models
    Contains the data models used by the engine.
pieces
    Contains the piece data and piece manipulation functions.
utils
    Contains utility functions used by the engine.

"""

from . import models, pieces, utils
from .models import (
    MOVES,
    PIECES,
    AttackTable,
    Block,
    Board,
    ClearedLine,
    ClearEvent,
    ClearName,
    DamageTankedEvent,
    Event,
    GameOverEvent,
    GarbageLine,
    Move,
    Options,
    Piece,
    PieceData,
    PiecePlacedEvent,
    ScoreData,
    ScoreInfo,
    Statistics,
)
from .move_generator import generate_moves
from .pieces import (
    FAST_PIECE_MASKS,
    FAST_PIECE_MATRICES,
    PIECE_BORDERS,
    PIECE_MATRICES,
    WALLKICK,
    WALLKICKS,
    PieceMatrix,
    generate_bag,
    get_piece_border,
    get_piece_mask,
    get_piece_matrix,
)
from .tetris import TetrisGame
from .utils import (
    calculate_score,
    check_collision,
    check_immobile,
    check_pc,
    clear_lines,
    create_piece,
    generate_garbage,
    get_board_avg_height,
    get_board_bumpiness,
    get_board_heights,
    get_board_hole_and_ledge_count,
    get_board_hole_count,
    get_board_ledge_count,
    get_subgrid_mask,
    move_drop,
    move_left,
    move_right,
    process_garbage,
    rotate_ccw,
    rotate_cw,
    sonic_drop,
    sonic_left,
    sonic_right,
)

__all__ = [
    "models",
    "pieces",
    "utils",
    "TetrisGame",
    "Board",
    "Command",
    "DamageTankedEvent",
    "Event",
    "ClearEvent",
    "GameOverEvent",
    "GarbageLine",
    "Options",
    "Piece",
    "PieceData",
    "PiecePlacedEvent",
    "ScoreData",
    "ScoreInfo",
    "Statistics",
    "Move",
    "MOVES",
    "PIECES",
    "AttackTable",
    "ClearedLine",
    "ClearName",
    "GameAction",
    "Block",
    "WALLKICK",
    "WALLKICKS",
    "generate_bag",
    "get_piece_border",
    "get_piece_mask",
    "get_piece_matrix",
    "PIECE_BORDERS",
    "PIECE_MATRICES",
    "PieceMatrix",
    "FAST_PIECE_MASKS",
    "FAST_PIECE_MATRICES",
    "generate_garbage",
    "get_board_avg_height",
    "get_board_bumpiness",
    "get_board_heights",
    "get_board_hole_count",
    "get_board_ledge_count",
    "get_board_hole_and_ledge_count",
    "get_subgrid_mask",
    "process_garbage",
    "calculate_score",
    "check_collision",
    "check_immobile",
    "check_pc",
    "clear_lines",
    "create_piece",
    "rotate_ccw",
    "rotate_cw",
    "move_drop",
    "move_left",
    "move_right",
    "sonic_drop",
    "sonic_left",
    "sonic_right",
    "generate_moves",
]
