# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blockfish.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 3, "", "blockfish.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x62lockfish.proto\x12\tblockfish"5\n\x08Snapshot\x12\x0c\n\x04hold\x18\x01 \x01(\t\x12\r\n\x05queue\x18\x02 \x01(\t\x12\x0c\n\x04rows\x18\x03 \x03(\t"B\n\nSuggestion\x12\x0e\n\x06rating\x18\x01 \x01(\x12\x12$\n\x06inputs\x18\x02 \x03(\x0e\x32\x10.blockfish.InputB\x02\x10\x01"E\n\x05Stats\x12\r\n\x05nodes\x18\x01 \x01(\x04\x12\x12\n\niterations\x18\x02 \x01(\x04\x12\x19\n\x11time_taken_millis\x18\x03 \x01(\x04"\xf8\x02\n\x07Request\x12/\n\nset_config\x18\x01 \x01(\x0b\x32\x19.blockfish.Request.ConfigH\x00\x12\x31\n\x0bset_ruleset\x18\x02 \x01(\x0b\x32\x1a.blockfish.Request.RulesetH\x00\x12-\n\x07\x61nalyze\x18\x03 \x01(\x0b\x32\x1a.blockfish.Request.AnalyzeH\x00\x1aI\n\x06\x43onfig\x12\x12\n\nnode_limit\x18\x01 \x01(\r\x12\x13\n\x0bmax_results\x18\x03 \x01(\r\x12\x16\n\x0emax_placements\x18\x04 \x01(\r\x1aJ\n\x07Ruleset\x12-\n\x03srs\x18\x01 \x01(\x0b\x32\x1e.blockfish.Request.Ruleset.SRSH\x00\x1a\x05\n\x03SRSB\t\n\x07ruleset\x1a<\n\x07\x41nalyze\x12\n\n\x02id\x18\x01 \x01(\x03\x12%\n\x08snapshot\x18\x02 \x01(\x0b\x32\x13.blockfish.SnapshotB\x05\n\x03req"\x85\x02\n\x08Response\x12\x30\n\x08greeting\x18\x01 \x01(\x0b\x32\x1c.blockfish.Response.GreetingH\x00\x12\x30\n\x08\x66inished\x18\x02 \x01(\x0b\x32\x1c.blockfish.Response.AnalysisH\x00\x1a)\n\x08Greeting\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04motd\x18\x02 \x01(\t\x1a\x63\n\x08\x41nalysis\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x1f\n\x05stats\x18\x02 \x01(\x0b\x32\x10.blockfish.Stats\x12*\n\x0bsuggestions\x18\x03 \x03(\x0b\x32\x15.blockfish.SuggestionB\x05\n\x03res*G\n\x05Input\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\x12\x06\n\x02\x43W\x10\x02\x12\x07\n\x03\x43\x43W\x10\x03\x12\x08\n\x04HOLD\x10\x04\x12\x06\n\x02SD\x10\x05\x12\x06\n\x02HD\x10\x06\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "blockfish_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SUGGESTION"].fields_by_name["inputs"]._loaded_options = None
    _globals["_SUGGESTION"].fields_by_name["inputs"]._serialized_options = b"\020\001"
    _globals["_INPUT"]._serialized_start = 867
    _globals["_INPUT"]._serialized_end = 938
    _globals["_SNAPSHOT"]._serialized_start = 30
    _globals["_SNAPSHOT"]._serialized_end = 83
    _globals["_SUGGESTION"]._serialized_start = 85
    _globals["_SUGGESTION"]._serialized_end = 151
    _globals["_STATS"]._serialized_start = 153
    _globals["_STATS"]._serialized_end = 222
    _globals["_REQUEST"]._serialized_start = 225
    _globals["_REQUEST"]._serialized_end = 601
    _globals["_REQUEST_CONFIG"]._serialized_start = 383
    _globals["_REQUEST_CONFIG"]._serialized_end = 456
    _globals["_REQUEST_RULESET"]._serialized_start = 458
    _globals["_REQUEST_RULESET"]._serialized_end = 532
    _globals["_REQUEST_RULESET_SRS"]._serialized_start = 516
    _globals["_REQUEST_RULESET_SRS"]._serialized_end = 521
    _globals["_REQUEST_ANALYZE"]._serialized_start = 534
    _globals["_REQUEST_ANALYZE"]._serialized_end = 594
    _globals["_RESPONSE"]._serialized_start = 604
    _globals["_RESPONSE"]._serialized_end = 865
    _globals["_RESPONSE_GREETING"]._serialized_start = 716
    _globals["_RESPONSE_GREETING"]._serialized_end = 757
    _globals["_RESPONSE_ANALYSIS"]._serialized_start = 759
    _globals["_RESPONSE_ANALYSIS"]._serialized_end = 858
# @@protoc_insertion_point(module_scope)
