[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "botris-interface"
version = "0.1.0"
description = "A python interface library to easily create bots to connect to botrisbattle.com"
authors = [
    { name="Nathanael Lu", email="info@lunathanael.dev" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"

[project.urls]
"Repository" = "https://github.com/lunathanael/botris-interface"

[tool.setuptools.packages.find]
where = ["botris"]
