name: Feature request
description: Check instructions for submitting your idea first.
title: "ENH: <Please write a comprehensive title after the 'ENH: ' prefix>"

body:
- type: markdown
  attributes:
    value: >
      If you're looking to request a new feature or change in functionality,
      including adding or changing the meaning of arguments to an existing
      function, please post your idea on the
      [discord](https://discord.gg/NUSgpfT5eH)
      to explain your reasoning in addition to opening an issue or pull request.

- type: textarea
  attributes:
    label: "Proposed new feature or change:"
  validations:
    required: true
