name: Post-install/importing issue
description: Report an issue if you have trouble importing or using botris-interface after installation.
title: "<Please write a comprehensive title here>"
labels: [32 - Installation]

body:
- type: textarea
  attributes:
    label: "Steps to reproduce:"
    description: >
      Please describe the installation method (e.g. building from source,
      Anaconda, pip), your OS and botris/Python version information.
  validations:
    required: true

- type: textarea
  attributes:
    label: "Error message:"
    description: >
      Please include full error message, if any.
    placeholder: |
      << Full traceback starting from `Traceback: ...` >>
    render: shell

- type: textarea
  attributes:
    label: "Additional information:"
    description: Please add any additional information that could help us diagnose the problem better.
